### ISSUE TITLE
O teclado demora muito para reconhecer sequências.

### ISSUE THREAD

**Issue by arthurcazevedo** [stherzada/piano--project#3]
O teclado só está reconhecendo a sequência de notas assim que ele abre. Por exemplo, abrindo a página e teclando qqq funciona, mas depois não funciona mais, e se se ao abrir a página começar com qualquer outra nota que não seja de uma das sequências conhecidas, também não funciona. Parece que existe um timer para ele voltar a reconhecer as sequências.

**Comment by stherzada** [comment]
Oi, é proposital! Pra ter esse delay perante ao reconhecimento, por ter notas parecidas em alguns dos casos que irei colocar, e para aplicação não "bugar" e a pessoa tocar infinitamente varias notas sem bater no json das músicas.

**Comment by arthurcazevedo** [comment]
Ahhhhhhhhhhhhhhhhh ok

Devo ter pulado essa parte do manual....
